export const ONTARIO_COUNTIES: string[] = [
  "Middlesex",
  "Algoma",
  "Brant",
  "Bruce",
  "Chatham-Kent",
  "Cochrane",
  "Dufferin",
  "Durham",
  "Elgin",
  "Essex",
  "Frontenac",
  "Grey",
  "Haliburton",
  "Halton",
  "Hamilton",
  "Hastings",
  "Huron",
  "Kawartha Lakes",
  "Kenora",
  "Lambton",
  "Lanark",
  "Leeds and Grenville",
  "Lennox and Addington",
  "Manitoulin",
  "Muskoka",
  "Niagara",
  "Nipissing",
  "Norfolk",
  "Northumberland",
  "Ottawa",
  "Oxford",
  "Parry Sound",
  "Peel",
  "Perth",
  "Peterborough",
  "Prescott and Russell",
  "Prince Edward",
  "Rainy River",
  "Renfrew",
  "Simcoe",
  "Stormont, Dundas and Glengarry",
  "Sudbury",
  "Thunder Bay",
  "Timiskaming",
  "Toronto",
  "Waterloo",
  "Wellington",
  "York",
];
